defmodule ClaudeLive.Repo.Migrations.InitialSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:worktrees, primary_key: false) do
      add :project_id,
          references(:projects, column: :id, name: "worktrees_project_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :branch, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:sessions, primary_key: false) do
      add :worktree_id,
          references(:worktrees, column: :id, name: "sessions_worktree_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :cwd, :text, null: false
      add :status, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:projects, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :path, :text, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop table(:projects)

    drop constraint(:sessions, "sessions_worktree_id_fkey")

    drop table(:sessions)

    drop constraint(:worktrees, "worktrees_project_id_fkey")

    drop table(:worktrees)
  end
end