defmodule ClaudeLive.Repo.Migrations.RenameProjectToRepository do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # alter table(:worktrees) do
    # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
    # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
    # remove :project_id
    # end
    # 

    create table(:repositories, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :path, :text, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    alter table(:worktrees) do
      add :repository_id,
          references(:repositories,
            column: :id,
            name: "worktrees_repository_id_fkey",
            type: :uuid
          ),
          null: false
    end
  end

  def down do
    alter table(:worktrees) do
      remove :repository_id
    end

    drop table(:repositories)

    drop constraint(:worktrees, "worktrees_repository_id_fkey")

    # alter table(:worktrees) do
    # This is the `down` migration of the statement:
    #
    #     remove :project_id
    #
    # 
    # add :project_id, references(:projects, column: :id, name: "worktrees_project_id_fkey", type: :uuid), null: false
    # end
    # 
  end
end