defmodule ClaudeLive.Repo.Migrations.UpdateSessionSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # alter table(:sessions) do
    # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
    # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
    # remove :cwd
    # end
    # 
  end

  def down do
    # alter table(:sessions) do
    # This is the `down` migration of the statement:
    #
    #     remove :cwd
    #
    # 
    # add :cwd, :text, null: false
    # end
    # 
  end
end
