defmodule ClaudeLive.Repo.Migrations.AddUniqueIndexToWorktrees do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:worktrees, [:repository_id, :branch],
             name: "worktrees_unique_branch_per_repository_index"
           )
  end

  def down do
    drop_if_exists unique_index(:worktrees, [:repository_id, :branch],
                     name: "worktrees_unique_branch_per_repository_index"
                   )
  end
end
