defmodule ClaudeLive.Repo.Migrations.AddPathToWorktrees do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:worktrees) do
      add :path, :text
    end
  end

  def down do
    alter table(:worktrees) do
      remove :path
    end
  end
end